const recipes = [
  {
    name: "Oskars glutenfria frukostrutor",
    ingredients: [
      "500 g Semper Mix (spara ca 1 dl till utbakning)",
      "3 dl fingervarmt vatten",
      "50 g jäst",
      "1 tsk salt",
      "0,5 dl pofiber",
      "1 dl Fibrex (finns numer endast malen, testa ev boveteflingor eller havregryn, eller uteslut)",
      "1 dl neutral olja",
      "ca 2 msk ljus sirap, kan bytas mot honung eller socker (eller uteslutes)",
      "1,5 tsk Lindroos SoftBake",
      "ca 1 dl riven ost",
    ],
    instructions: [
      "Sätt ugnen på 230 grader (varmluftsugn 225 grader).",
      "Lös upp jästen i vattnet med salt och ev sirap.",
      "Tillsätt pofiber och ev Fibrex och låt det svälla i ca 15 minuter.",
      "Tillsätt oljan och rör om.",
      "Häll upp mjölet i en annan bunke och blanda ner Softbake. Ta inte all mjölmix direkt, glutenfri deg får gärna vara lite lös och kladdig.",
      "Blanda ner i detvätskan och blanda till en lagom fast deg, lite kladdig men hanterbar.",
      "Täck bunken med plastfolie (förhindrar att degen torkar) och gärna en handduk, och låt jäsa på dragfri plats i ca 30 minuter.",
      "Strö lite av den återstående mjölmixen på en bänk, ta upp degen och knåda ihop lite och tryck ut till en rektangel.",
      "Ta en ugnssäker form som är ca 20 x 30 cm och lägg i ett bakplåtspapper (om man skrynklar ihop det och slätar ut så är det enklare), strö lite mjölmix på pappret och lägg dit degen. Tryck ut så den täcker formen för att få jämna rutor.",
      "Pensla med kallt vatten, strö på ost och ytterligare lite mjölmix.",
      "Täck med plastfolie och handduk och låt jäsa ytterligare 30-45 minuter.",
      "Grädda mitt i ugnen ca 15-20 minuter tills brödet har fått en gyllene färg och är genomgräddat.",
    ],
    notes: [
      "Låt brödet svalna innan det skärs upp så är det mindre ris att det smular. Skär i rutor och frys in det som inte ska ätas de närmaste dagarna.",
      "Om man är osäker på om brödet är färdiggräddat kan man lyfta ur det försiktigt och knacka i botten - det ska låta lite ihåligt.",
    ],
  },
  {
    name: "Saftig tefflimpa med lingon",
    ingredients: [
      "25 g jäst för matbröd",
      "6 dl kallt vatten",
      "1 dl lingonsylt (klämflaska om man inte vill ha synliga lingon i brödet)",
      "4 msk mörk sirap",
      "400 g (ca 7,2 dl) teffjöl",
      "200 g (ca 2,4 dl) potatismjöl",
      "40 g (4 msk) mald psyllium",
      "2 tsk salt",
      "ev 2 tsk SoftBake",
      "3 tsk mortlade anisfrön",
      "3 tsk mortlade fänkålsfrön",
    ],
    instructions: [
      "Lös upp jästen i det kalla vattnet.",
      "Mät/väg upp övriga ingredienser och tillsätt vartefter.",
      "Rör samman allt för hand eller i assistent så det blir ordentligt blandat. Se till att inget mjöl ligger kvar torrt och oblandat. Degen ska vara ganska lös.",
      "Täck bunken med plastfolie och en handduk och låt vila på dragfri plats i ca 10-15 minuter.",
      "Sätt ugnen på 250 grader (varmluft 230 grader)",
      "Lägg bakplåtspapper på en plåt och strö eventuellt på lite teffmjöl eller potatismjöl.",
      "Blöt en skärbräda och händerna och ta upp degen och forma till två avlånga limpor som läggs på plåten.",
      "Pensla eventuellt med vatten och grädda mitt i ugnen i 40 minuter.",
      "Låt limporna svalna innan de skärs upp.",
    ],
    notes: [
      "Observera att det ska vara vanlig mörk sirap, inte brödsirap då den innehåller malt och därmed inte är glutenfri.",
      "Tillsätt 2 tsk pomerans och 1 tsk malen nejlika om man vill ha vörtbröd.",
      "Tillsätt 1-2 tsk kummin om man vill ha mer som kavring.",
      "Vill man ha ett okryddat bröd går det utmärkt att utesluta.",
      "Orginalreceptet innehåller ingen lingonsylt, vill man utesluta den tillsätts 1 dl vatten extra.",
      "SoftBake består av växtfibrer som gör att jästbröd får mer struktur som vanligt bröd med gluten. Det går bra att utesluta.",
    ],
  },
  {
    name: "Black bean brownies",
    ingredients: [
      "230 g avrunna, svarta bönor",
      "100 g mörk choklad (alt ljus choklad för mildare smak)",
      "3 ägg",
      "2-3 msk kakao",
      "1 dl socker (alt 10 urkärnade dadlar)",
      "ev 1 tsk vanillapaste",
      "2 tsk salt",
      "en påse Odense chokladknappar eller motsvarande mängd hackad choklad att blanda i eller strö på efter att smeten har mixats klart",
    ],
    instructions: [
      "Sätt ugnen på 175 grader (varmluft)",
      "Lägg dadlarna i blöt 10-15 minuter (i vatten eller kaffe beroende på smak)",
      "Skölj bönorna noga (tills vattnet är klart) och låt rinna av",
      "Smält chokladen i vattenbad, lägg ned smöret också (allt ska ändå mixas tillsammans)",
      "Lägg alla ingredienser i en matberedare med kniven monterad och mixa till en jämn och fin smet.",
      "Blanda ner hälften av chokladknapparna/hackad choklad och rör om med en slev.",
      "Häll smeten i en springform klädd med bakplåtspapper occh strö över resten av chokladen.",
      "Grädda mitt i ugnen i ca 20-25 minuter.",
      "Låt kakan svalna helt innan den skärs i bitar.",
      "Förvaras och serveras kall.",
    ],
    notes: [
      "Med ljus choklad blir det en lenare smak (jag använder ofta 90% chokladhalt så den blir ganska kraftig i smaken). Det går bra att blanda mörk och ljus choklad om man föredrar det.",
      "Strö eventuellt på grovt hackade nötter innan kakan gräddas.",
      "Smält mer choklad och ringla över den avsvalnade kakan. Mörk, ljus, vit - any way you like it.",
    ],
  },
];

export default recipes;
